[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Takeru Hayashi", email = "takeruhayashi@g.ucla.edu" }
]
dependencies = [
    "jupyter>=1.1.1",
    "lab>=8.3",
    "tqdm>=4.66.5",
    "django>=5.1.2",
    "dashi>=0.0.0",
    "pydashi>=2.0.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/analysis"]
